### ISSUE TITLE
Shooting sound effects stops after the first enemy dies.

### ISSUE THREAD

**Issue by cwillu** [kiwphi/pop-shoot#14]
Console shows “[Intervention] Blocked attempt to create a WebMediaPlayer as there are too many WebMediaPlayers already in existence. See crbug.com/1144736#c27” when this occurs.

**Comment by kiwphi** [comment]
Can you reproduce it or did it just happen once? Could you give more details on O/S & browser version?

**Comment by cwillu** [comment]
If I start firing immediately, the firing sound consistently breaks (with the mentioned console message) right before the first enemy has exploded.

**Comment by kiwphi** [comment]
It seems like this is happening because the browser has reached the maximum audio events the current tab can handle.... which shouldn't happen because the [AudioController](https://github.com/kiwphi/pop-shoot/blob/main/modules/Logic/Controllers/AudioController.js) puts a limit on sounds that might reach a high number of cloned instances.
A quick search shows that Chrome v92 might have had a bug that prevented some audio events to properly end. Which version are you using and on which OS ?

**Comment by dlsso** [comment]
Fwiw, I could not reproduce on Chrome v112 or Brave 1.50 in Windows 10.

**Comment by kiwphi** [comment]
Unable to reproduce on most combinations of O/S & browsers
