### ISSUE TITLE
A more standardized README.md

### ISSUE THREAD

**Issue by ToniMaunde** [kiwphi/pop-shoot#24]
Hi. I believe the project could benefit from embracing a conventional README structure, especially to provide clear instructions on how to run the project, etc. The same could be said about the CONTRIBUTING.md file.

**Comment by kiwphi** [comment]
Hello @ToniMaunde,

Do you have any suggestions regarding the README? I didn't include instructions for running the project because there are 2 kinds of persons who might visit:
- Non-technical persons, who just want to play. There's a "Play" button just for that. No need to do anything else.
- Developers who might want to clone and modify/contribute. Since it's just a static website which doesn't to follow any build process, I assume that any Javascript developer can locally host it without any fuss. There's no need to even setup apache/nginx anymore, if one is using VSCode for example, there are plugins for that (Live Server etc...)

As for the CONTRIBUTING.md file, I agree that it can be more elaborate, I will be modifying it and adding to it as I work on the project. If you have any suggestions or would like to contribute to anything specific let me know and I'll be glad to help.

**Comment by ToniMaunde** [comment]
I do, even though I'm bias towards this structure (since I embraced it in my projects). It would be something like this: https://github.com/ToniMaunde/react-svg-component

> Non-technical persons, who just want to play. There's a "Play" button just for that. No need to do anything else.
I understand this, but I can't help to think that most folks coming to Github will be technical, so having a technical structure in place would benefit the project.

> Since it's just a static website which doesn't to follow any build process, I assume that any Javascript developer can locally host it without any fuss.
Silly me. I saw the script file and the yaml one and assumed there was something I was missing to run the project.

> If you have any suggestions or would like to contribute to anything specific
I'll be work on the point to raised regarding the legibility and logic within the EnemyController class, hopefully I can make a PR before the weekend.
